### PR TITLE
Added step to jspm install in readme docs

### PR DESCRIPTION
**Pull request by togakangaroo**
Would also be a good idea to just check for this in the gulp setup and install there

Solution to the issue here https://github.com/alexweber/es6-jspm-gulp-boilerplate/issues/3

### CODE REVIEW

**Comment by alexweber** [comment]
@togakangaroo Awesome, good catch, thanks for tracking that down! :+1:

**Comment by alexweber** [comment]
PS - This PR is to your fork's master!  I created new one to mine and merged already: https://github.com/alexweber/es6-jspm-gulp-boilerplate/pull/4

Thanks again!

**Comment by togakangaroo** [comment]
Whoops. I saw a new option on the interface, got excited and clicked it.
Guess it didn't do what I thought. Thanks!

**Comment by alexweber** [comment]
@togakangaroo No worries! PS - you get those tests running ok now?

**Comment by togakangaroo** [comment]
Yes they do. Might have follow up questions when u get back to it but the
basics are working

**Comment by alexweber** [comment]
Awesome, glad to hear it :)

It's very much a work in progress, once I get a couple projects in I'll probably wanna improve a lotta stuff :)  Let me know, happy to incorporate feedback!  Thx

**Pull request closed without merging**
